In [2]:
import pandas as pd

In [46]:
hum = pd.read_csv('./forecast_humidity_0729.csv', encoding='cp949')
temp = pd.read_csv('./forecast_temperature_0729.csv', encoding='cp949')
temp

       avg_temp area         tma  max_temp  min_temp
0     -2.344048   강원  2012-01-01       5.0      -7.3
1     -3.010000   경기  2012-01-01       1.0      -6.9
2      1.642857   경남  2012-01-01       7.0      -2.9
3      0.075556   경북  2012-01-01       6.1      -5.9
4      0.383333   광주  2012-01-01       3.0      -0.9
...         ...  ...         ...       ...       ...
30220  2.666684   전남  2016-12-31       9.0      -4.7
30221  1.019392   전북  2016-12-31       7.5      -7.0
30222  7.058615   제주  2016-12-31      10.5       2.5
30223  1.146847   충남  2016-12-31       7.7      -4.0
30224 -0.256306   충북  2016-12-31       5.2      -6.8

[30225 rows x 5 columns]

In [30]:
area_name = [
'서울',
'부산',
'대구',
'인천',
'광주',
'대전',
'울산',
'세종',
'경기',
'강원',
'충북',
'충남',
'전북',
'전남',
'경북',
'경남',
'제주',
]

In [57]:
hum_df = pd.DataFrame(columns=['area','tma','min_humidity','max_humidity','avg_humidity'])
for area in area_name:
    hum2 = hum[hum['area']==area]
    hum2['tma'] = pd.to_datetime(hum2['tma'])
    head_range = pd.date_range(start='2012-01-01', end='2016-12-31')
    hum2.index = hum2['tma']
    hum3 = hum2.reindex(head_range, fill_value=None)
    hum3['tma'] = hum3.index
    hum3.reset_index(drop=True, inplace=True)
    hum3.insert(2, 'yyyy', hum3.tma.dt.year)
    hum3.insert(3, 'mm',   hum3.tma.dt.month)
    hum3.insert(4, 'dd',   hum3.tma.dt.day)
    hum3['area'] = area
    hum_df = pd.concat([hum_df, hum3], axis=0)

hum_df.sort_values(['tma', 'area'], inplace=True)
hum_df.reset_index(drop=True, inplace=True)
hum_df['tma'] = pd.to_datetime(hum_df['tma'])
hum_df

/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/815631091.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hum2['tma'] = pd.to_datetime(hum2['tma'])

,area,tma,min_humidity,max_humidity,avg_humidity,yyyy,mm,dd
0,강원,2012-01-01,30.0,95.0,58.333333,2012.0,1.0,1.0
1,경기,2012-01-01,38.0,65.0,50.733333,2012.0,1.0,1.0
2,경남,2012-01-01,31.0,78.0,44.916667,2012.0,1.0,1.0
3,경북,2012-01-01,20.0,90.0,52.377778,2012.0,1.0,1.0
4,광주,2012-01-01,70.0,85.0,75.833333,2012.0,1.0,1.0
...,...,...,...,...,...,...,...,...
31054,전남,2016-12-31,40.0,89.0,65.555094,2016.0,12.0,31.0
31055,전북,2016-12-31,45.0,87.0,72.161486,2016.0,12.0,31.0
31056,제주,2016-12-31,45.0,76.0,60.569257,2016.0,12.0,31.0
31057,충남,2016-12-31,54.0,95.0,75.118243,2016.0,12.0,31.0
31058,충북,2016-12-31,55.0,90.0,72.665541,2016.0,12.0,31.0

In [59]:
hum_df.isnull().sum()

area               0
tma                0
min_humidity    1188
max_humidity    1188
avg_humidity    1188
yyyy               0
mm                 0
dd                 0
dtype: int64

In [54]:
temp_df = pd.DataFrame(columns=['area','tma','min_temp','max_temp','avg_temp'])
for area in area_name:
    temp2 = temp[temp['area']==area]
    temp2['tma'] = pd.to_datetime(temp2['tma'])
    head_range = pd.date_range(start='2012-01-01', end='2016-12-31')
    temp2.index = temp2['tma']
    temp3 = temp2.reindex(head_range, fill_value=None)
    temp3['tma'] = temp3.index
    temp3.reset_index(drop=True, inplace=True)
    temp3.insert(2, 'yyyy', temp3.tma.dt.year)
    temp3.insert(3, 'mm',   temp3.tma.dt.month)
    temp3.insert(4, 'dd',   temp3.tma.dt.day)
    temp3['area'] = area
    temp_df = pd.concat([temp_df, temp3], axis=0)

temp_df.sort_values(['tma', 'area'], inplace=True)
temp_df.reset_index(drop=True, inplace=True)
temp_df['tma'] = pd.to_datetime(temp_df['tma'])
temp_df

/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])
/var/folders/f5/x0_185757lld2fhv6ygmb8f40000gn/T/ipykernel_26195/3177306142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['tma'] = pd.to_datetime(temp2['tma'])

      area        tma min_temp max_temp  avg_temp    yyyy    mm    dd
0       강원 2012-01-01     -7.3      5.0 -2.344048  2012.0   1.0   1.0
1       경기 2012-01-01     -6.9      1.0     -3.01  2012.0   1.0   1.0
2       경남 2012-01-01     -2.9      7.0  1.642857  2012.0   1.0   1.0
3       경북 2012-01-01     -5.9      6.1  0.075556  2012.0   1.0   1.0
4       광주 2012-01-01     -0.9      3.0  0.383333  2012.0   1.0   1.0
...    ...        ...      ...      ...       ...     ...   ...   ...
31054   전남 2016-12-31     -4.7      9.0  2.666684  2016.0  12.0  31.0
31055   전북 2016-12-31     -7.0      7.5  1.019392  2016.0  12.0  31.0
31056   제주 2016-12-31      2.5     10.5  7.058615  2016.0  12.0  31.0
31057   충남 2016-12-31     -4.0      7.7  1.146847  2016.0  12.0  31.0
31058   충북 2016-12-31     -6.8      5.2 -0.256306  2016.0  12.0  31.0

[31059 rows x 8 columns]

In [58]:
temp_df.isnull().sum()

area          0
tma           0
min_temp    834
max_temp    834
avg_temp    834
yyyy          0
mm            0
dd            0
dtype: int64