In [1]:
import pandas as pd
from itertools import *
from pycaret.regression import *

In [66]:
dataset2 = pd.read_csv('./hospital_male_0802_test.csv', encoding='cp949')
dataset2.mm = dataset2.mm.astype('int64')
dataset2 = dataset2[~dataset2['tma'].astype(str).str.contains('2011-|2016-')].reset_index(drop=True)
# tmp_df = dataset2.shift(periods=527)
# tmp_df

In [65]:
# dataset2.drop(columns=['frequency'], inplace=True)
# dataset2 = pd.concat([dataset2, tmp_df[['frequency']]], axis=1)
# dataset2.to_csv('hospital_male_0802_test.csv', encoding='cp949', index=False)

In [67]:

fixed_df = dataset2[['area', 'mm', 'weekday', 'frequency','heat_wave', 'cold_wave','total_pop', 'elderly_ratio','pm10','diff_hum','diff_temp','avg_ps', 'so2']]

sub_df = [ dataset2[['o3']], dataset2[['avg_age']], dataset2[['avg_temp']], dataset2[['min_max_ps']], dataset2[['sum_rn']], dataset2[['avg_hum']] ]
sub_list = list(combinations(sub_df, 2))
sub_list[2][0]
number = 1

for i in range(len(sub_df)):
    sub_list = list(combinations(sub_df, i+1))
    for j in range(len(sub_list)):
        print('number: ', number)
        dataset_df = fixed_df.copy()
        for k in sub_list[j]:
            dataset_df = pd.concat([dataset_df,k], axis=1)
        
        print(dataset_df.columns)
        data = dataset_df.sample(frac=0.9, random_state=786) 
        data_unseen = dataset_df.drop(data.index) 

        data.reset_index(drop=True, inplace=True) 
        data_unseen.reset_index(drop=True, inplace=True) 

        print('Data for Modeling: ' + str(data.shape)) 
        print('Unseen Data For Predictions: ' + str(data_unseen.shape)) 
        
        s = setup(data, target = 'frequency', session_id=123)
        
        best_model_5 = compare_models(sort='RMSE', n_select = 5)
        
        final_model = finalize_model(best_model_5[0])
        prediction = predict_model(final_model, data = data_unseen)
        print(prediction['Label'])
        print('='*100)
        number += 1

number:  1
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3'],
      dtype='object')
Data for Modeling: (22353, 14)
Unseen Data For Predictions: (2484, 14)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.364156
1       0.903340
2       1.194785
3       1.355174
4       1.269545
          ...
2479    1.193908
2480    1.284011
2481    4.663092
2482    1.471474
2483    1.071348
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  2
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age'],
      dtype='object')
Data for Modeling: (22353, 14)
Unseen Data For Predictions: (2484, 14)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.328676
1       0.892152
2       1.171910
3       1.344103
4       1.268625
          ...
2479    1.193417
2480    1.276992
2481    4.650835
2482    1.470436
2483    1.067818
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  3
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp'],
      dtype='object')
Data for Modeling: (22353, 14)
Unseen Data For Predictions: (2484, 14)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.359611
1       0.901916
2       1.195357
3       1.348985
4       1.268881
          ...
2479    1.183750
2480    1.281417
2481    4.657951
2482    1.475691
2483    1.066016
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  4
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 14)
Unseen Data For Predictions: (2484, 14)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.353018
1       0.899394
2       1.193546
3       1.344306
4       1.274880
          ...
2479    1.177706
2480    1.274060
2481    4.650564
2482    1.471393
2483    1.059863
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  5
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 14)
Unseen Data For Predictions: (2484, 14)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.359710
1       0.902126
2       1.193466
3       1.352266
4       1.265075
          ...
2479    1.172670
2480    1.273787
2481    4.653376
2482    1.469358
2483    1.060993
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  6
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 14)
Unseen Data For Predictions: (2484, 14)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.359479
1       0.910403
2       1.196952
3       1.355670
4       1.271821
          ...
2479    1.174182
2480    1.274034
2481    4.644437
2482    1.475041
2483    1.060299
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  7
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.337519
1       0.898142
2       1.176612
3       1.353635
4       1.266497
          ...
2479    1.209863
2480    1.284806
2481    4.660288
2482    1.471564
2483    1.078768
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  8
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.361274
1       0.898541
2       1.188580
3       1.352883
4       1.268012
          ...
2479    1.188170
2480    1.281875
2481    4.660843
2482    1.467956
2483    1.067290
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  9
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.363350
1       0.903114
2       1.194522
3       1.354951
4       1.269088
          ...
2479    1.193078
2480    1.283358
2481    4.661614
2482    1.470885
2483    1.070783
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  10
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.368737
1       0.908018
2       1.198259
3       1.361617
4       1.262987
          ...
2479    1.188512
2480    1.281436
2481    4.662675
2482    1.470436
2483    1.071591
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  11
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.370206
1       0.914676
2       1.198041
3       1.367100
4       1.265584
          ...
2479    1.189648
2480    1.283443
2481    4.655152
2482    1.474523
2483    1.071424
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  12
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.336183
1       0.897132
2       1.176605
3       1.350221
4       1.262008
          ...
2479    1.202034
2480    1.285392
2481    4.658147
2482    1.476313
2483    1.076115
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  13
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.328466
1       0.892112
2       1.172022
3       1.344009
4       1.268336
          ...
2479    1.192697
2480    1.276526
2481    4.649795
2482    1.470008
2483    1.067364
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  14
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.337087
1       0.901386
2       1.182766
3       1.351723
4       1.266390
          ...
2479    1.191366
2480    1.274557
2481    4.651388
2482    1.471576
2483    1.070021
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  15
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.334987
1       0.901249
2       1.176413
3       1.352712
4       1.266650
          ...
2479    1.189117
2480    1.276235
2481    4.644965
2482    1.472970
2483    1.067219
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  16
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.358618
1       0.901622
2       1.195022
3       1.348681
4       1.268557
          ...
2479    1.182800
2480    1.280549
2481    4.656224
2482    1.474906
2483    1.065300
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  17
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.363210
1       0.907810
2       1.200934
3       1.354790
4       1.266514
          ...
2479    1.179692
2480    1.276958
2481    4.656346
2482    1.474227
2483    1.066053
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  18
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.361548
1       0.910409
2       1.197338
3       1.356652
4       1.269162
          ...
2479    1.176972
2480    1.277138
2481    4.647789
2482    1.476388
2483    1.062855
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  19
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.359055
1       0.906338
2       1.199854
3       1.352061
4       1.269827
          ...
2479    1.175729
2480    1.272258
2481    4.651342
2482    1.471393
2483    1.062197
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  20
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.358616
1       0.910144
2       1.196640
3       1.355488
4       1.271225
          ...
2479    1.173374
2480    1.273360
2481    4.642821
2482    1.474327
2483    1.059745
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  21
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 15)
Unseen Data For Predictions: (2484, 15)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.362041
1       0.911023
2       1.201166
3       1.356818
4       1.269051
          ...
2479    1.174662
2480    1.272694
2481    4.649335
2482    1.473401
2483    1.062529
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  22
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.337114
1       0.897043
2       1.174513
3       1.354410
4       1.268150
          ...
2479    1.210838
2480    1.283314
2481    4.660035
2482    1.468079
2483    1.078429
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  23
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.337326
1       0.898082
2       1.176664
3       1.353519
4       1.266308
          ...
2479    1.209277
2480    1.284442
2481    4.659519
2482    1.471262
2483    1.078395
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  24
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.345221
1       0.906390
2       1.185851
3       1.361121
4       1.263268
          ...
2479    1.207663
2480    1.282683
2481    4.660973
2482    1.472267
2483    1.080802
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  25
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.343862
1       0.907278
2       1.181136
3       1.362286
4       1.264513
          ...
2479    1.205563
2480    1.284053
2481    4.654404
2482    1.474109
2483    1.078177
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  26
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.360263
1       0.898307
2       1.188346
3       1.352558
4       1.267784
          ...
2479    1.187254
2480    1.280977
2481    4.659092
2482    1.467214
2483    1.066580
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  27
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.364888
1       0.908366
2       1.199264
3       1.360246
4       1.273461
          ...
2479    1.189314
2480    1.274044
2481    4.658367
2482    1.464513
2483    1.068647
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  28
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.364695
1       0.917508
2       1.196396
3       1.368747
4       1.277724
          ...
2479    1.182899
2480    1.270689
2481    4.641745
2482    1.465889
2483    1.063188
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  29
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.367947
1       0.907869
2       1.198117
3       1.361386
4       1.262651
          ...
2479    1.187793
2480    1.280796
2481    4.661237
2482    1.469917
2483    1.071075
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  30
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.369408
1       0.914427
2       1.197777
3       1.366852
4       1.265151
          ...
2479    1.188854
2480    1.282811
2481    4.653738
2482    1.473943
2483    1.070876
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  31
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.372916
1       0.915351
2       1.202304
3       1.368392
4       1.262717
          ...
2479    1.190314
2480    1.282201
2481    4.660217
2482    1.472862
2483    1.073804
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  32
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.335900
1       0.897025
2       1.176626
3       1.350045
4       1.261907
          ...
2479    1.201327
2480    1.284882
2481    4.657216
2482    1.475884
2483    1.075622
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  33
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.341229
1       0.903070
2       1.183209
3       1.355659
4       1.260232
          ...
2479    1.196908
2480    1.280875
2481    4.656606
2482    1.474877
2483    1.075452
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  34
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.338443
1       0.902169
2       1.178567
3       1.354537
4       1.262426
          ...
2479    1.197202
2480    1.282852
2481    4.652320
2482    1.476674
2483    1.073658
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  35
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.336869
1       0.901308
2       1.182806
3       1.351628
4       1.266080
          ...
2479    1.190671
2480    1.274126
2481    4.650410
2482    1.471153
2483    1.069583
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  36
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.334785
1       0.901226
2       1.176535
3       1.352633
4       1.266352
          ...
2479    1.188377
2480    1.275759
2481    4.643895
2482    1.472539
2483    1.066755
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  37
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.337937
1       0.902719
2       1.182149
3       1.353800
4       1.264933
          ...
2479    1.190104
2480    1.274733
2481    4.649870
2482    1.471831
2483    1.069643
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  38
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.362238
1       0.907518
2       1.200603
3       1.354490
4       1.266200
          ...
2479    1.178768
2480    1.276114
2481    4.654661
2482    1.473462
2483    1.065354
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  39
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.360532
1       0.910159
2       1.197003
3       1.356388
4       1.268828
          ...
2479    1.175943
2480    1.276210
2481    4.645932
2482    1.475579
2483    1.062092
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  40
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.363842
1       0.911027
2       1.201494
3       1.357673
4       1.266736
          ...
2479    1.177095
2480    1.275405
2481    4.652250
2482    1.474580
2483    1.064755
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  41
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 16)
Unseen Data For Predictions: (2484, 16)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.361214
1       0.910774
2       1.200861
3       1.356642
4       1.268487
          ...
2479    1.173890
2480    1.272054
2481    4.647785
2482    1.472722
2483    1.061997
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  42
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp', 'min_max_ps'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.336849
1       0.896943
2       1.174534
3       1.354241
4       1.268051
          ...
2479    1.210168
2480    1.282839
2481    4.659163
2482    1.467686
2483    1.077966
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  43
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.342301
1       0.904470
2       1.183855
3       1.359247
4       1.267349
          ...
2479    1.204760
2480    1.278176
2481    4.657770
2482    1.468193
2483    1.077305
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  44
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.343756
1       0.909862
2       1.179667
3       1.366290
4       1.271294
          ...
2479    1.200755
2480    1.276033
2481    4.646039
2482    1.466726
2483    1.072993
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  45
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.345042
1       0.906331
2       1.185892
3       1.361012
4       1.263099
          ...
2479    1.207134
2480    1.282355
2481    4.660276
2482    1.471993
2483    1.080463
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  46
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.343673
1       0.907229
2       1.181196
3       1.362178
4       1.264316
          ...
2479    1.204956
2480    1.283679
2481    4.653608
2482    1.473802
2483    1.077794
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  47
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.346786
1       0.908732
2       1.186851
3       1.363349
4       1.262804
          ...
2479    1.206508
2480    1.282535
2481    4.659279
2482    1.472968
2483    1.080571
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  48
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.363951
1       0.908085
2       1.198948
3       1.359950
4       1.273150
          ...
2479    1.188412
2480    1.273237
2481    4.656745
2482    1.463792
2483    1.067972
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  49
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.363557
1       0.912307
2       1.191446
3       1.365930
4       1.270043
          ...
2479    1.178363
2480    1.273353
2481    4.642828
2482    1.466487
2483    1.061950
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  50
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.367155
1       0.918361
2       1.200662
3       1.370161
4       1.275491
          ...
2479    1.183197
2480    1.268705
2481    4.646171
2482    1.463714
2483    1.065159
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  51
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.372161
1       0.915116
2       1.202049
3       1.368157
4       1.262314
          ...
2479    1.189565
2480    1.281609
2481    4.658880
2482    1.472319
2483    1.073285
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  52
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.340942
1       0.902962
2       1.183231
3       1.355480
4       1.260129
          ...
2479    1.196187
2480    1.280355
2481    4.655658
2482    1.474440
2483    1.074949
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  53
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.338176
1       0.902123
2       1.178604
3       1.354418
4       1.262307
          ...
2479    1.196357
2480    1.282266
2481    4.651227
2482    1.476211
2483    1.073088
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  54
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.341007
1       0.903530
2       1.184028
3       1.355424
4       1.261165
          ...
2479    1.197337
2480    1.280672
2481    4.656415
2482    1.475158
2483    1.075389
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  55
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.337747
1       0.902696
2       1.182255
3       1.353725
4       1.264660
          ...
2479    1.189418
2480    1.274295
2481    4.648876
2482    1.471434
2483    1.069212
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  56
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_temp', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 17)
Unseen Data For Predictions: (2484, 17)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.362865
1       0.910786
2       1.201167
3       1.357418
4       1.266421
          ...
2479    1.176110
2480    1.274519
2481    4.650465
2482    1.473808
2483    1.064022
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  57
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp', 'min_max_ps', 'sum_rn'],
      dtype='object')
Data for Modeling: (22353, 18)
Unseen Data For Predictions: (2484, 18)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.342030
1       0.904361
2       1.183863
3       1.359079
4       1.267236
          ...
2479    1.204079
2480    1.277698
2481    4.656887
2482    1.467787
2483    1.076836
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  58
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp', 'min_max_ps', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 18)
Unseen Data For Predictions: (2484, 18)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.343477
1       0.909831
2       1.179730
3       1.366168
4       1.271194
          ...
2479    1.199857
2480    1.275395
2481    4.644862
2482    1.466231
2483    1.072383
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  59
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 18)
Unseen Data For Predictions: (2484, 18)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.346408
1       0.910780
2       1.184069
3       1.367718
4       1.269119
          ...
2479    1.200881
2480    1.274012
2481    4.650399
2482    1.464553
2483    1.074858
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  60
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 18)
Unseen Data For Predictions: (2484, 18)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.346615
1       0.908687
2       1.186900
3       1.363252
4       1.262630
          ...
2479    1.205967
2480    1.282202
2481    4.658565
2482    1.472696
2483    1.080227
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  61
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_temp', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 18)
Unseen Data For Predictions: (2484, 18)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.366188
1       0.918121
2       1.200340
3       1.369905
4       1.275176
          ...
2479    1.182221
2480    1.267833
2481    4.644410
2482    1.462956
2483    1.064434
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  62
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'avg_age', 'avg_temp', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 18)
Unseen Data For Predictions: (2484, 18)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.340756
1       0.903486
2       1.184058
3       1.355313
4       1.261055
          ...
2479    1.196549
2480    1.280129
2481    4.655394
2482    1.474728
2483    1.074857
Name: Label, Length: 2484, dtype: float64
====================================================================================================
number:  63
Index(['area', 'mm', 'weekday', 'frequency', 'heat_wave', 'cold_wave',
       'total_pop', 'elderly_ratio', 'pm10', 'diff_hum', 'diff_temp', 'avg_ps',
       'so2', 'o3', 'avg_age', 'avg_temp', 'min_max_ps', 'sum_rn', 'avg_hum'],
      dtype='object')
Data for Modeling: (22353, 19)
Unseen Data For Predictions: (2484, 19)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

0       4.346146
1       0.910750
2       1.184125
3       1.367603
4       1.269028
          ...
2479    1.200044
2480    1.273419
2481    4.649298
2482    1.464093
2483    1.074287
Name: Label, Length: 2484, dtype: float64
====================================================================================================

In [ ]:
data